#ifndef RETROJUUYON_CONFIG_H
#define RETROJUUYON_CONFIG_H

#ifndef RETROJUUYON_HAVE_AUDIO
#define RETROJUUYON_HAVE_AUDIO 1
#endif

#ifndef RETROJUUYON_SAFETY
#define RETROJUUYON_SAFETY 1
#endif

#endif
